# Generated by Django 2.2.7 on 2019-12-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
